/**
 * @description       :
 * @author            : Remario Richards
 * @group             :
 * @last modified on  : 09-18-2023
 * @last modified by  : Remario Richards
 **/
public class Constants {
  public static final String ACTIVE = 'Active';
  public static final String QUEUE_TEXT = 'Queue';

  public static final String ENTSTNDSUPP = ' Standard Support';
  public static final String ENTENHPROCESS = ' Enhancement Process';
  public static final String ENTHOTFIXROCESS = ' Hotfix Process';
  public static final String GROUPNEWPHOENIXCASES = 'New Phoenix Cases';

  public static final String INSLANO = 'No';
  public static final String INSLAYES = 'Yes';

  public static final String GENERAL_SUPPORT_CASE_TYPE = 'General Support';
  public static final String ENHANCEMENT_CASE_TYPE = 'Enhancement';
  public static final String HOTFIX_CASE_TYPE = 'Hotfix';

  public static final String STD_CLIENT_PAGE_RECORD_TYPE = 'Client_Page_Layout';
  public static final String STD_PHOENIX_RECORD_TYPE = 'Standard_Case_Process_Pheonix';
  public static final String ENHANCEMENT_RECORD_TYPE = 'Enhancements';
  public static final String HOTFIX_RECORD_TYPE = 'Hotfix';
  public static final String CHILD_CASE_RECORD_TYPE = 'Child_Case_Question';

  public static final String SUBSTATUS_CLIENT_MOVE_FORWARD_YES = 'Client move forward:YES';
  public static final String SUBSTATUS_CLIENT_MOVE_FORWARD_NO = 'Client move forward:NO';
  public static final String SUBSTATUS_TECH_REVIEW_IS_REQUIRED = 'Technical Review is required';
  public static final String SUBSTATUS_DEVELOPMENT = 'Development';
  public static final String SUBSTATUS_PENDING_RESOLUTION = 'Pending Resolution Verification';
  public static final String SUBSTATUS_AWAIT_DEVELOPMENT = 'Awaiting Development';
  public static final String SUBSTATUS_AWAIT_FRS = 'Awaiting FRS';
  public static final String SUBSTATUS_GAP_DOC_CREATION_UPDATE = 'Gap Document Creation / Update';
  public static final String SUBSTATUS_FRS_CREATION = 'FRS Creation';
  public static final String SUBSTATUS_WO_CREATED_YES = 'Work Order Created : YES';
  public static final String SUBSTATUS_GAP_DOC_IS_COMPLETED = 'Gap Document is completed';
  public static final String SUBSTATUS_ADD_INFO_NO = 'Additional Information : NO';
  public static final String SUBSTATUS_ADD_INFO_YES = 'Additional Information : YES';
  public static final String SUBSTATUS_READY_FOR_BOARD_REVIEW1 = 'Ready_for_Board_Review';
  public static final String SUBSTATUS_READY_FOR_BOARD_REVIEW2 = 'Ready for Board Review';
  public static final String SUBSTATUS_FIX_COMPLETE = 'Fix Complete';
  public static final String SUBSTATUS_FIX_COMPLETE_PENDING_APPROVAL = 'Fix Complete - Pending Approval';
  public static final String SUBSTATUS_FIX_COMPLETE_PENDING_REJECTED = 'Fix Complete -  Rejected';

  public static final String QUEUE_L1_SUPPORT = 'L1 Support';
  public static final String QUEUE_TECH_SUPPORT_L2 = 'Technical Support L2';
  public static final String QUEUE_ESCALATION_SUPPORT_TEAM = 'Escalation Support Team';
  public static final String QUEUE_PRODUCT_SPECIALIST = 'Product Specialist';
  public static final String QUEUE_DEVELOPMENT = 'Development';
  public static final String QUEUE_ACCOUNT_MGR = 'Account Manager';
  public static final String QUEUE_HOT_FIX_COMMITTEE = 'Hot Fix Committee';
  public static final String QUEUE_SUPPORT_SPL_L2 = 'Support Specialist L2';

  public static final String CASE_STATUS_CLOSED = 'Closed';

  public static final String CASE_DECISION_VALUE_REJECTED = 'Rejected';
  public static final String CASE_DECISION_VALUE_APPROVED = 'Approved';
  public static final String CASE_DECISION_VALUE_TABLED = 'Tabled';

  public static final String CASE_DELIVERY_VALUE_CRITICALHOTFIXALL = 'Critical Hotfix All';
  public static final String CASE_DELIVERY_VALUE_BANKFIX = 'Bank Fix';
  public static final String CASE_DELIVERY_VALUE_SCRIPTAPPROVAL_STND = 'Script Approval - Standard';
  public static final String CASE_DELIVERY_VALUE_SCRIPTAPPROVAL_SEVER = 'Script Approval - Severe';

  public static final String CASE_ACNAME_NOTAVAILABLE = 'NA';
  public static final String LEAD_STATUS_NEW = 'New';
  public static final String OPP_QUALIFICATION = 'Qualification';
  public static final String OPP_SUBJECT = 'New Opportunity for case number: ';

  public static final String MILESTONE_NO_SLA = 'Standard Support Process : No SLA';
  public static final String MILESTONE_STD_SUPPRT_PROCESS_LOW = 'Standard Support Process : LOW';
  public static final String MILESTONE_STD_PRC_ESCALATION_TEAM = 'Standard Process : Escalation Team (';
  public static final String MILESTONE_STD_PRC_REVIEW_CASE = 'Standard Support : Review Case (';
  public static final String MILESTONE_ENH_REVIEW_CASE = 'Enhancement Review Case (';
  public static final String MILESTONE_ENH_SRS_BRS_REVISION = 'SRS/BRS: Revision (';
  public static final String MILESTONE_ENH_SRS_BRS_NEED_ADD_INFO = 'SRS/BRS : Needs Additional Information (';
  public static final String MILESTONE_ENH_WO_CREATION = 'Work Order Creation: ';
  public static final String MILESTONE_ENH_GAP_DOC_WO_REVIEW = 'Gap Document and Work Order : Review (';
  public static final String MILESTONE_ENH_FRS_CREATION = 'FRS Creation (';
  public static final String MILESTONE_ENH_AWAIT_FRS = 'Awaiting FRS (';
  public static final String MILESTONE_ENH_RELEASE_DATE_WORK_COMPLETED = 'Release Date added and Work Completed: ';
  public static final String MILESTONE_HOTFIX_POST_BOARD_DEVELOPMENT = 'Post Board Developement';
  public static final String MILESTONE_HOTFIX_BOARD_REVIEW_INDECISION = 'Board Review : Indecision';
  public static final String MILESTONE_HOTFIX_BOARD_REVIEW = 'Hotfix: Board Review';
  public static final String MILESTONE_HOTFIX_BNKFIX_REL_SENT_TO_CLIENT = 'Bank Fix : Release Sent to Client';
  public static final String MILESTONE_HOTFIX_DELIVERY_BANK_FIX = 'Delivery : Bank Fix';
  public static final String MILESTONE_HOTFIX_DELIVERY_ALL_CLIENTS = 'Delivery : Critical Hot Fix - All Clients';
  public static final String MILESTONE_HOTFIX_REVIEW_CASE = 'Hotfix Review Case (';
  public static final String MILESTONE_HOTFIX_DEV_CREATES_SCRIPT = 'Developer Creates Script';
  public static final String MILESTONE_HOTFIX_SCRIPT_COMPLETE_RUN_SCRIPT = 'Script Complete : Run Script';
  public static final String MILESTONE_HOTFIX_CRITICAL_SUPPORT_CREATES_SCRIPT = 'CRITICAL : Support Creates Script';
  public static final String MILESTONE_HOTFIX_SUPPORT_CREATES_SCRIPT_HIGH = 'Support Creates Script: HIGH';
  public static final String MILESTONE_HOTFIX_SCRIPT_APPROVAL_PENDING = 'Script Complete : Pending Approval';

  public static final String CASE_PRIORIY_LOW = 'Low';
  public static final String CASE_PRIORIY_MEDIUM = 'Medium';
  public static final String CASE_PRIORIY_HIGH = 'High';
  public static final String CASE_PRIORIY_CRITICAL = 'Critical';

  public static final String TEMPLATE_CASE_ASSIGN = 'SUPPORTNewassignmentnotificationSAMPLE';
  public static final String TEMPLATE_NO_SLA = 'Case_Email_Template_No_SLA';
  public static final String TEMPLATE_NO_SLA_MOVE_FORWARD_NO = 'Case_Close_Notification';
  public static final String TEMPLATE_NO_SLA_MOVE_FORWARD_YES = 'Case_Close_Notification_Yes';
  public static final String TEMPLATE_CASE_ESCALATION = 'Case_Escalation_Email_Notification';
  public static final String TEMPLATE_CASE_WO_AND_GAP = 'Case_WO_and_Gap_Email_Template';
  public static final String TEMPLATE_CASE_RELEASE_DATE_TIMELINE_TO_CLIENT = 'Case_Release_Date_And_timeline_to_client';
  public static final String TEMPLATE_SEND_HOTFIX_CASE_TO_DEV = 'Send_Hot_Fix_Case_Details_to_Developer';
  public static final String TEMPLATE_HOTFIX_CAUSE_SCEN_SOL_PROB = 'HotFix_Template_contains_Cause_Scenario_Problem_and_solution';
  public static final String TEMPLATE_BANK_FIX_CRITICAL_HOTFIX = 'Bank_Fix_Critical_Hotfix_Template';
  public static final String TEMPLATE_SEND_HOTFIX_CASE_RELEASE_DETAILS = 'Send_Hot_Fix_Case_Release_Details_to_Client';
  public static final String TEMPLATE_SEND_HOTFIX_CASE_REJECTION = 'Send_Hot_Fix_Case_Rejection_to_Client';
  public static final String TEMPLATE_SEND_HOTFIX_CASE_FIXED_STATUS = 'Send_Hot_Fix_Case_Fixed_Status_to_Client';
  public static final String TEMPLATE_SRS_BRS_DOC = 'SRS_BRS_Docs';
  public static final String TEMPLATE_CASE_DEVELOPER_QUESTION_ANSWERED = 'Case_Developer_Question_Answered';
  public static final String DEFAULT_BUSINESS_HOURS_NAME = 'JN Business Hours';
}